#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "demotape.y".
#

require 'racc/parser.rb'


module DemoTape
  class Parser < Racc::Parser

module_eval(<<'...end demotape.y/module_eval...', 'demotape.y', 513)
  def parse(str, file: "<unknown>")
    @file = file
    @lexer = DemoTape::Lexer.new
    @tokens = @lexer.tokenize(str)
    @token_index = 0
    do_parse
  end

  def next_token
    token = @tokens.shift
    @current_token_index = @token_index
    @token_index += 1
    token
  end

  def make_token(type, value, index)
    line_info = @lexer.line_map[index] || {}
    token_class = case type
                  when :identifier then Token::Identifier
                  when :string then Token::String
                  when :number then Token::Number
                  when :duration then Token::Duration
                  when :regex then Token::Regex
                  when :time_unit then Token::TimeUnit
                  when :operator then Token::Operator
                  when :space then Token::Space
                  when :leading_space then Token::LeadingSpace
                  when :trailing_space then Token::TrailingSpace
                  when :keyword then Token::Keyword
                  else Token::Base
                  end

    token_class.new(
      value,
      line: line_info[:line],
      column: line_info[:column],
      raw: line_info[:raw]
    )
  end

  def attach_location(command, duration_index: nil)
    line_info = @lexer.line_map[@command_start_index] || {}
    command.line = line_info[:line]
    command.column = line_info[:column]
    command.line_content = line_info[:content]
    command.file = @file

    # Attach duration/speed/timeout specific columns if provided
    if duration_index
      duration_info = @lexer.line_map[duration_index] || {}
      command.duration_column = duration_info[:column]
    end

    command
  end

  def on_error(token_id, token_value, value_stack)
    # Get line metadata from the lexer's line map
    line_info = @lexer.line_map[@current_token_index] || {}
    line_num = line_info[:line] || "?"
    col_num = line_info[:column] || 1
    line_content = line_info[:content] || ""

    token_name = token_to_str(token_id) || token_id.to_s

    error_msg = "Unexpected token #{token_name.inspect} at #{@file}:#{line_num}:#{col_num}:\n"
    error_msg += "  #{line_content}\n"
    error_msg += "  #{' ' * (col_num - 1)}^"

    raise DemoTape::ParseError, error_msg
  end

...end demotape.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
   -51,    98,    99,    97,    79,    51,    61,    52,    53,    62,
    54,     8,    57,    58,    77,    77,    87,    84,    15,    85,
     4,     5,     7,    57,    58,    19,   -17,    10,    11,     7,
    12,    13,     7,   -17,    35,    21,   -17,    90,    37,    91,
    36,    57,    58,    92,    34,    38,     7,    57,    58,    39,
    64,    29,    30,    65,   -49,    98,    99,    97,   -48,    98,
    99,    97,    47,    19,     7,    98,    99,    97,    98,    99,
    97,    98,    99,    97,    29,    30,    29,    30,    29,    30,
    29,    30,    29,    30,    70,    19,    29,    30,    29,    30,
    29,    30,    29,    30,    29,    30,    24,    25,    19,    44,
    45,    19,    50,    60,    63,    66,    67,    68,    69,    73,
    76,    77,    78,    82,    83,    94,    95,   101,   102,   104,
   106,   108,   110,   112 ]

racc_action_check = [
    85,    85,    85,    85,    60,    35,    37,    35,    35,    37,
    35,     1,    35,    35,    85,    60,    76,    76,     4,    76,
     0,     0,     0,    76,    76,     6,     0,     2,     2,     2,
     3,     3,     3,     2,    19,     8,     3,    78,    19,    78,
    19,    78,    78,    79,    18,    20,    18,    79,    79,    20,
    39,    16,    16,    39,   104,   104,   104,   104,   108,   108,
   108,   108,    32,     9,    32,   102,   102,   102,   106,   106,
   106,   110,   110,   110,    17,    17,    22,    22,    23,    23,
    26,    26,    27,    27,    46,    46,    48,    48,    49,    49,
    71,    71,    72,    72,    84,    84,    10,    12,    14,    28,
    31,    33,    34,    36,    38,    40,    41,    42,    43,    47,
    51,    53,    59,    74,    75,    80,    81,    96,   100,   103,
   105,   107,   109,   111 ]

racc_action_pointer = [
    18,    11,    25,    28,    15,   nil,    17,   nil,    35,    55,
    93,   nil,    94,   nil,    90,   nil,    46,    69,    42,    28,
    39,   nil,    71,    73,   nil,   nil,    75,    77,    96,   nil,
   nil,    97,    60,    93,    99,    -3,    92,    -2,    93,    42,
   102,   103,   104,   105,   nil,   nil,    77,   106,    81,    83,
   nil,   104,   nil,    94,   nil,   nil,   nil,   nil,   nil,   106,
    -2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    85,    87,   nil,   110,   111,     8,   nil,    26,    32,
   112,   113,   nil,   nil,    89,    -3,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   114,   nil,   nil,   nil,
   104,   nil,    61,   108,    51,   106,    64,   110,    55,   108,
    67,   112,   nil ]

racc_action_default = [
    -3,   -64,    -1,    -2,   -64,    -6,   -64,   -16,   -64,   -64,
   -64,   -15,   -64,    -7,   -64,    -4,   -20,   -20,   -17,   -56,
   -37,   113,   -20,   -20,   -14,    -5,   -20,   -20,   -64,   -18,
   -19,   -64,   -17,   -64,   -64,   -64,   -64,   -64,   -64,   -64,
   -64,   -64,   -64,   -64,    -8,   -10,   -64,   -64,   -20,   -20,
   -31,   -64,   -35,   -38,   -46,   -54,   -55,   -61,   -62,   -44,
   -43,   -57,   -58,   -36,   -59,   -60,    -9,   -11,   -12,   -13,
   -25,   -20,   -20,   -32,   -64,   -64,   -64,   -63,   -64,   -64,
   -64,   -64,   -27,   -29,   -20,   -24,   -50,   -52,   -53,   -39,
   -40,   -45,   -41,   -42,   -28,   -30,   -64,   -21,   -22,   -23,
   -64,   -26,   -24,   -64,   -24,   -64,   -24,   -64,   -24,   -64,
   -24,   -64,   -47 ]

racc_goto_table = [
    28,    31,    55,    56,    59,     1,    40,    41,     2,    16,
    42,    43,    22,    17,     3,    32,    23,    26,   nil,   nil,
     6,    27,     9,    14,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    74,    75,   nil,   nil,    48,   nil,    33,   nil,
    49,   100,   nil,    88,    86,    89,    93,   nil,   nil,    71,
   nil,   nil,    46,    72,   nil,    80,    81,   nil,   103,   nil,
   105,   nil,   107,   nil,   109,   nil,   111,   nil,    96 ]

racc_goto_check = [
     6,     6,    13,    12,    12,     1,     6,     6,     2,     5,
     6,     6,     5,     7,     3,    10,     7,     5,   nil,   nil,
     4,     7,     4,     4,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     6,     6,   nil,   nil,     5,   nil,     4,   nil,
     7,     8,   nil,    13,    12,    13,    13,   nil,   nil,     5,
   nil,   nil,     4,     7,   nil,     6,     6,   nil,     8,   nil,
     8,   nil,     8,   nil,     8,   nil,     8,   nil,     6 ]

racc_goto_pointer = [
   nil,     5,     8,    14,    20,     3,   -16,     7,   -44,   nil,
    -3,   nil,   -32,   -33 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,
   nil,    20,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 19, :_reduce_1,
  1, 19, :_reduce_2,
  0, 19, :_reduce_3,
  2, 21, :_reduce_4,
  3, 21, :_reduce_5,
  1, 21, :_reduce_6,
  2, 21, :_reduce_7,
  4, 20, :_reduce_8,
  5, 20, :_reduce_9,
  4, 20, :_reduce_10,
  5, 20, :_reduce_11,
  5, 20, :_reduce_12,
  5, 20, :_reduce_13,
  3, 20, :_reduce_14,
  2, 20, :_reduce_15,
  1, 22, :_reduce_16,
  0, 22, :_reduce_17,
  1, 24, :_reduce_18,
  1, 24, :_reduce_19,
  0, 24, :_reduce_20,
  1, 26, :_reduce_21,
  1, 26, :_reduce_22,
  1, 26, :_reduce_23,
  0, 26, :_reduce_24,
  4, 25, :_reduce_25,
  7, 27, :_reduce_26,
  4, 28, :_reduce_27,
  5, 28, :_reduce_28,
  4, 28, :_reduce_29,
  5, 28, :_reduce_30,
  2, 28, :_reduce_31,
  3, 28, :_reduce_32,
  1, 24, :_reduce_33,
  0, 24, :_reduce_34,
  3, 23, :_reduce_35,
  3, 23, :_reduce_36,
  1, 23, :_reduce_37,
  3, 23, :_reduce_38,
  5, 23, :_reduce_39,
  5, 23, :_reduce_40,
  5, 23, :_reduce_41,
  5, 23, :_reduce_42,
  3, 23, :_reduce_43,
  3, 23, :_reduce_44,
  5, 23, :_reduce_45,
  3, 23, :_reduce_46,
  17, 23, :_reduce_47,
  13, 23, :_reduce_48,
  9, 23, :_reduce_49,
  5, 23, :_reduce_50,
  5, 23, :_reduce_51,
  5, 23, :_reduce_52,
  5, 23, :_reduce_53,
  3, 23, :_reduce_54,
  3, 23, :_reduce_55,
  1, 23, :_reduce_56,
  3, 29, :_reduce_57,
  3, 29, :_reduce_58,
  3, 29, :_reduce_59,
  3, 29, :_reduce_60,
  1, 31, :_reduce_61,
  1, 31, :_reduce_62,
  2, 30, :_reduce_63 ]

racc_reduce_n = 64

racc_shift_n = 113

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMENT => 2,
  :NEWLINE => 3,
  :LEADING_SPACE => 4,
  :TRAILING_SPACE => 5,
  :SPACE => 6,
  :END => 7,
  :IDENTIFIER => 8,
  :DO => 9,
  :PLUS => 10,
  :NUMBER => 11,
  :AT => 12,
  :REGEX => 13,
  :COMMA => 14,
  :STRING => 15,
  :WORD => 16,
  :TIME_UNIT => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMENT",
  "NEWLINE",
  "LEADING_SPACE",
  "TRAILING_SPACE",
  "SPACE",
  "END",
  "IDENTIFIER",
  "DO",
  "PLUS",
  "NUMBER",
  "AT",
  "REGEX",
  "COMMA",
  "STRING",
  "WORD",
  "TIME_UNIT",
  "$start",
  "tape",
  "commands",
  "metadata",
  "leading_space",
  "command",
  "trailing_space",
  "block",
  "optional_space",
  "block_start",
  "block_commands",
  "key_combo",
  "duration",
  "string" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'demotape.y', 2)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 3)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 4)
  def _reduce_3(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 6)
  def _reduce_4(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 7)
  def _reduce_5(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 8)
  def _reduce_6(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 9)
  def _reduce_7(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 11)
  def _reduce_8(val, _values, result)
     result = [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 12)
  def _reduce_9(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 13)
  def _reduce_10(val, _values, result)
     result = [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 14)
  def _reduce_11(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 15)
  def _reduce_12(val, _values, result)
     result = [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 16)
  def _reduce_13(val, _values, result)
     result = [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 17)
  def _reduce_14(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 18)
  def _reduce_15(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 20)
  def _reduce_16(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 21)
  def _reduce_17(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 23)
  def _reduce_18(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 24)
  def _reduce_19(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 25)
  def _reduce_20(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 27)
  def _reduce_21(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 28)
  def _reduce_22(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 29)
  def _reduce_23(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 30)
  def _reduce_24(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 33)
  def _reduce_25(val, _values, result)
               cmd = val[0]
           cmd.children.replace(val[1])
           result = cmd.prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 39)
  def _reduce_26(val, _values, result)
               # When this rule is being reduced:
           # val[0] = first IDENTIFIER value
           # val[1] = first SPACE value
           # val[2] = second IDENTIFIER value
           # val[3] = second SPACE value
           # val[4] = DO value
           # val[5] = trailing_space (nil or SPACE value)
           # val[6] = NEWLINE value
           
           # @token_index is AFTER consuming NEWLINE
           # We need to count backwards to find each token's position
           
           # trailing_space can be 0 or 1 token
           trailing_consumed = val[5].nil? ? 0 : 1
           
           # Working backwards from @token_index:
           # @token_index points to NEXT token (after NEWLINE)
           # @token_index - 1 = NEWLINE
           # @token_index - 2 = trailing_space (if present) or DO (if not)
           # So: @token_index - 1 - trailing_consumed = DO
           #     @token_index - 2 - trailing_consumed = SPACE before DO
           #     @token_index - 3 - trailing_consumed = second IDENTIFIER
           #     @token_index - 4 - trailing_consumed = first SPACE
           #     @token_index - 5 - trailing_consumed = first IDENTIFIER
           
           identifier_index = @token_index - 6 - trailing_consumed
           space1_index = @token_index - 5 - trailing_consumed
           name_index = @token_index - 4 - trailing_consumed
           space2_index = @token_index - 3 - trailing_consumed
           do_index = @token_index - 2 - trailing_consumed
           
           @command_start_index = identifier_index
           
           tokens = [
             make_token(:identifier, val[0], identifier_index),
             make_token(:space, val[1], space1_index),
             make_token(:identifier, val[2], name_index),
             make_token(:space, val[3], space2_index),
             make_token(:keyword, val[4], do_index)
           ]

           cmd = DemoTape::Command.new(val[0], val[2], children: [])
           cmd.tokens = tokens
           result = attach_location(cmd)

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 85)
  def _reduce_27(val, _values, result)
     result = [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 86)
  def _reduce_28(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 87)
  def _reduce_29(val, _values, result)
     result = [val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 88)
  def _reduce_30(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 89)
  def _reduce_31(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 90)
  def _reduce_32(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 92)
  def _reduce_33(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 93)
  def _reduce_34(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 96)
  def _reduce_35(val, _values, result)
                 space_index = @token_index - 2
             line_info = @lexer.line_map[space_index] || {}
             error_msg = "Unexpected token \"SPACE\" at #{@file}:#{line_info[:line]}:#{line_info[:column]}:\n"
             error_msg += "  #{line_info[:content]}\n"
             error_msg += "  #{' ' * (line_info[:column] - 1)}^"
             raise DemoTape::ParseError, error_msg

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 104)
  def _reduce_36(val, _values, result)
                 @command_start_index = @last_key_index
             keys = val[0][:keys]
             key_tokens = val[0][:tokens]
             command_name = keys.shift

             tokens = key_tokens + [
               make_token(:space, val[1], @token_index - 2),
               make_token(:number, val[2], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(command_name, "", keys:, count: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 119)
  def _reduce_37(val, _values, result)
                 @command_start_index = @last_key_index
             keys = val[0][:keys]
             key_tokens = val[0][:tokens]
             command_name = keys.shift

             cmd = DemoTape::Command.new(command_name, "", keys:)
             cmd.tokens = key_tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 129)
  def _reduce_38(val, _values, result)
                 @command_start_index = @token_index - 4
             duration_index = @token_index - 2
             space_index = @token_index - 3

             tokens = [
               make_token(:identifier, val[0], @token_index - 4),
               make_token(:space, val[1], space_index),
               make_token(:number, val[2], @token_index - 2)
             ]

             # Duration commands (Sleep, Wait) treat bare numbers as seconds
             # Key commands treat numbers as repeat counts
             if ["Sleep", "Wait"].include?(val[0])
               cmd = DemoTape::Command.new(val[0], "#{val[2]}s")
               cmd.tokens = tokens
               result = attach_location(cmd, duration_index: duration_index).prepare!
             else
               cmd = DemoTape::Command.new(val[0], "", count: val[2])
               cmd.tokens = tokens
               result = attach_location(cmd).prepare!
             end

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 152)
  def _reduce_39(val, _values, result)
                 @command_start_index = @token_index - 6
             duration_index = @token_index - 3  # TIME_UNIT position

             tokens = [
               make_token(:identifier, val[0], @token_index - 6),
               make_token(:operator, "@", @token_index - 5),
               make_token(:duration, val[2], @token_index - 4),
               make_token(:space, val[3], @token_index - 2),
               make_token(:string, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], val[4], duration: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 168)
  def _reduce_40(val, _values, result)
                 @command_start_index = @token_index - 6
             duration_index = @token_index - 3  # TIME_UNIT position

             tokens = [
               make_token(:identifier, val[0], @token_index - 6),
               make_token(:operator, "@", @token_index - 5),
               make_token(:duration, val[2], @token_index - 4),
               make_token(:space, val[3], @token_index - 2),
               make_token(:number, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], "", duration: val[2], count: val[4])
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 184)
  def _reduce_41(val, _values, result)
                 @command_start_index = @token_index - 5
             duration_index = @token_index - 3

             tokens = [
               make_token(:identifier, val[0], @token_index - 5),
               make_token(:operator, "@", @token_index - 4),
               make_token(:number, val[2], @token_index - 3),
               make_token(:space, val[3], @token_index - 2),
               make_token(:number, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], "", duration: "#{val[2]}s", count: val[4])
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 200)
  def _reduce_42(val, _values, result)
                 @command_start_index = @token_index - 5
             duration_index = @token_index - 3

             tokens = [
               make_token(:identifier, val[0], @token_index - 5),
               make_token(:operator, "@", @token_index - 4),
               make_token(:number, val[2], @token_index - 3),
               make_token(:space, val[3], @token_index - 2),
               make_token(:string, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], val[4], duration: "#{val[2]}s")
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 216)
  def _reduce_43(val, _values, result)
                 @command_start_index = @token_index - 3
             duration_index = @token_index - 1

             tokens = [
               make_token(:identifier, val[0], @token_index - 3),
               make_token(:operator, "@", @token_index - 2),
               make_token(:number, val[2], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], "", duration: "#{val[2]}s")
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 230)
  def _reduce_44(val, _values, result)
                 @command_start_index = @token_index - 4
             duration_index = @token_index - 1  # TIME_UNIT position

             tokens = [
               make_token(:identifier, val[0], @token_index - 4),
               make_token(:operator, "@", @token_index - 3),
               make_token(:duration, val[2], @token_index - 2)
             ]

             cmd = DemoTape::Command.new(val[0], "", duration: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 244)
  def _reduce_45(val, _values, result)
                 @command_start_index = @token_index - 6
             duration_index = @token_index - 3  # TIME_UNIT position
             regex_index = @token_index - 1

             begin
               Regexp.new(val[4])
             rescue RegexpError => e
               line_info = @lexer.line_map[regex_index] || {}
               error_msg = "Invalid regex: #{e.message} at #{@file}:#{line_info[:line]}:#{line_info[:column]}:\n"
               error_msg += "  #{line_info[:content]}\n"
               error_msg += "  #{' ' * (line_info[:column] - 1)}^"
               raise DemoTape::ParseError, error_msg
             end

             tokens = [
               make_token(:identifier, val[0], @token_index - 6),
               make_token(:operator, "@", @token_index - 5),
               make_token(:duration, val[2], @token_index - 4),
               make_token(:space, val[3], @token_index - 2),
               make_token(:regex, val[4], regex_index)
             ]

             cmd = DemoTape::Command.new(val[0], val[4], duration: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index:).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 271)
  def _reduce_46(val, _values, result)
                 @command_start_index = @token_index - 3
             regex_index = @token_index - 1

             begin
               Regexp.new(val[2])
             rescue RegexpError => e
               line_info = @lexer.line_map[regex_index] || {}
               error_msg = "Invalid regex: #{e.message} at #{@file}:#{line_info[:line]}:#{line_info[:column]}:\n"
               error_msg += "  #{line_info[:content]}\n"
               error_msg += "  #{' ' * (line_info[:column] - 1)}^"
               raise DemoTape::ParseError, error_msg
             end

             tokens = [
               make_token(:identifier, val[0], @token_index - 3),
               make_token(:space, val[1], @token_index - 2),
               make_token(:regex, val[2], regex_index)
             ]

             cmd = DemoTape::Command.new(val[0], val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 295)
  def _reduce_47(val, _values, result)
                 @command_start_index = @token_index - 11

             # Build tokens array - for optional spaces, just create simple tokens
             tokens = []
             tokens << make_token(:identifier, val[0], @token_index - 11)
             tokens << make_token(:space, val[1], @token_index - 10)
             tokens << make_token(:identifier, val[2], @token_index - 9)
             tokens << make_token(:space, val[3], @token_index - 8)
             tokens << make_token(:number, val[4], @token_index - 7)
             tokens << DemoTape::Token::Space.new(val[5]) if val[5]
             tokens << DemoTape::Token::Operator.new(",")
             tokens << DemoTape::Token::Space.new(val[7]) if val[7]
             tokens << make_token(:number, val[8], @token_index - 5)
             tokens << DemoTape::Token::Space.new(val[9]) if val[9]
             tokens << DemoTape::Token::Operator.new(",")
             tokens << DemoTape::Token::Space.new(val[11]) if val[11]
             tokens << make_token(:number, val[12], @token_index - 3)
             tokens << DemoTape::Token::Space.new(val[13]) if val[13]
             tokens << DemoTape::Token::Operator.new(",")
             tokens << DemoTape::Token::Space.new(val[15]) if val[15]
             tokens << make_token(:number, val[16], @token_index - 1)

             cmd = DemoTape::Command.new(val[0], [val[4], val[8], val[12], val[16]], option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 322)
  def _reduce_48(val, _values, result)
                 @command_start_index = @token_index - 9

             tokens = []
             tokens << make_token(:identifier, val[0], @token_index - 9)
             tokens << make_token(:space, val[1], @token_index - 8)
             tokens << make_token(:identifier, val[2], @token_index - 7)
             tokens << make_token(:space, val[3], @token_index - 6)
             tokens << make_token(:number, val[4], @token_index - 5)
             tokens << DemoTape::Token::Space.new(val[5]) if val[5]
             tokens << DemoTape::Token::Operator.new(",")
             tokens << DemoTape::Token::Space.new(val[7]) if val[7]
             tokens << make_token(:number, val[8], @token_index - 3)
             tokens << DemoTape::Token::Space.new(val[9]) if val[9]
             tokens << DemoTape::Token::Operator.new(",")
             tokens << DemoTape::Token::Space.new(val[11]) if val[11]
             tokens << make_token(:number, val[12], @token_index - 1)

             cmd = DemoTape::Command.new(val[0], [val[4], val[8], val[12]], option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 344)
  def _reduce_49(val, _values, result)
                 @command_start_index = @token_index - 7

             tokens = []
             tokens << make_token(:identifier, val[0], @token_index - 7)
             tokens << make_token(:space, val[1], @token_index - 6)
             tokens << make_token(:identifier, val[2], @token_index - 5)
             tokens << make_token(:space, val[3], @token_index - 4)
             tokens << make_token(:number, val[4], @token_index - 3)
             tokens << DemoTape::Token::Space.new(val[5]) if val[5]
             tokens << DemoTape::Token::Operator.new(",")
             tokens << DemoTape::Token::Space.new(val[7]) if val[7]
             tokens << make_token(:number, val[8], @token_index - 1)

             cmd = DemoTape::Command.new(val[0], [val[4], val[8]], option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 362)
  def _reduce_50(val, _values, result)
                 @command_start_index = @token_index - 6

             tokens = [
               make_token(:identifier, val[0], @token_index - 6),
               make_token(:space, val[1], @token_index - 5),
               make_token(:identifier, val[2], @token_index - 4),
               make_token(:space, val[3], @token_index - 3),
               make_token(:duration, val[4], @token_index - 2)
             ]

             cmd = DemoTape::Command.new(val[0], val[4], option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 377)
  def _reduce_51(val, _values, result)
                 @command_start_index = @token_index - 5

             tokens = [
               make_token(:identifier, val[0], @token_index - 5),
               make_token(:space, val[1], @token_index - 4),
               make_token(:identifier, val[2], @token_index - 3),
               make_token(:space, val[3], @token_index - 2),
               make_token(:number, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], val[4].to_s, option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 392)
  def _reduce_52(val, _values, result)
                 @command_start_index = @token_index - 5

             tokens = [
               make_token(:identifier, val[0], @token_index - 5),
               make_token(:space, val[1], @token_index - 4),
               make_token(:identifier, val[2], @token_index - 3),
               make_token(:space, val[3], @token_index - 2),
               make_token(:identifier, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], val[4], option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 407)
  def _reduce_53(val, _values, result)
                 @command_start_index = @token_index - 5

             tokens = [
               make_token(:identifier, val[0], @token_index - 5),
               make_token(:space, val[1], @token_index - 4),
               make_token(:identifier, val[2], @token_index - 3),
               make_token(:space, val[3], @token_index - 2),
               make_token(:string, val[4], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], val[4], option: val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 422)
  def _reduce_54(val, _values, result)
                 @command_start_index = @token_index - 3

             tokens = [
               make_token(:identifier, val[0], @token_index - 3),
               make_token(:space, val[1], @token_index - 2),
               make_token(:string, val[2], @token_index - 1)
             ]

             cmd = DemoTape::Command.new(val[0], val[2])
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 435)
  def _reduce_55(val, _values, result)
                 @command_start_index = @token_index - 4
             duration_index = @token_index - 1  # TIME_UNIT position

             tokens = [
               make_token(:identifier, val[0], @token_index - 4),
               make_token(:space, val[1], @token_index - 3),
               make_token(:duration, val[2], @token_index - 2)
             ]

             cmd = DemoTape::Command.new(val[0], val[2])
             cmd.tokens = tokens
             result = attach_location(cmd, duration_index: duration_index).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 449)
  def _reduce_56(val, _values, result)
                 @command_start_index = @token_index - 1

             tokens = [make_token(:identifier, val[0], @token_index - 1)]

             # This could be a group invocation, mark it as such
             cmd = DemoTape::Command.new(val[0], "", group_invocation: true)
             cmd.tokens = tokens
             result = attach_location(cmd).prepare!

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 460)
  def _reduce_57(val, _values, result)
                   @last_key_index = @token_index - 1

               tokens = [
                 make_token(:identifier, val[0], @token_index - 3),
                 make_token(:operator, "+", @token_index - 2),
                 make_token(:identifier, val[2], @token_index - 1)
               ]

               result = { keys: [val[0], val[2]], tokens: tokens }

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 471)
  def _reduce_58(val, _values, result)
                   @last_key_index = @token_index - 1

               tokens = [
                 make_token(:identifier, val[0], @token_index - 3),
                 make_token(:operator, "+", @token_index - 2),
                 make_token(:number, val[2], @token_index - 1)
               ]

               result = { keys: [val[0], val[2].to_s], tokens: tokens }

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 482)
  def _reduce_59(val, _values, result)
                   @last_key_index = @token_index - 1

               tokens = val[0][:tokens] + [
                 make_token(:operator, "+", @token_index - 2),
                 make_token(:identifier, val[2], @token_index - 1)
               ]

               result = { keys: val[0][:keys] << val[2], tokens: tokens }

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 492)
  def _reduce_60(val, _values, result)
                   @last_key_index = @token_index - 1

               tokens = val[0][:tokens] + [
                 make_token(:operator, "+", @token_index - 2),
                 make_token(:number, val[2], @token_index - 1)
               ]

               result = { keys: val[0][:keys] << val[2].to_s, tokens: tokens }

    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 502)
  def _reduce_61(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 503)
  def _reduce_62(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'demotape.y', 505)
  def _reduce_63(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module DemoTape


